=== reearth/reearth-flow/workflow/schema/workflow.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Workflow",
  "type": "object",
  "required": [
    "entryGraphId",
    "graphs",
    "id",
    "name"
  ],
  "properties": {
    "entryGraphId": {
      "type": "string",
      "format": "uuid"
    },
    "graphs": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Graph"
      }
    },
    "id": {
      "type": "string",
      "format": "uuid"
    },
    "name": {
      "type": "string"
    },
    "with": {
      "type": [
        "object",
        "null"
      ],
      "additionalProperties": true
    }
  },
  "definitions": {
    "Edge": {
      "type": "object",
      "required": [
        "from",
        "fromPort",
        "id",
        "to",
        "toPort"
      ],
      "properties": {
        "from": {
          "type": "string",
          "format": "uuid"
        },
        "fromPort": {
          "type": "string"
        },
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "to": {
          "type": "string",
          "format": "uuid"
        },
        "toPort": {
          "type": "string"
        }
      }
    },
    "Graph": {
      "type": "object",
      "required": [
        "edges",
        "id",
        "name",
        "nodes"
      ],
      "properties": {
        "edges": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Edge"
          }
        },
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "type": "string"
        },
        "nodes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Node"
          }
        }
      }
    },
    "Node": {
      "oneOf": [
        {
          "type": "object",
          "required": [
            "action",
            "id",
            "name",
            "type"
          ],
          "properties": {
            "action": {
              "type": "string"
            },
            "id": {
              "type": "string",
              "format": "uuid"
            },
            "name": {
              "type": "string"
            },
            "type": {
              "type": "string",
              "enum": [
                "action"
              ]
            },
            "with": {
              "type": [
                "object",
                "null"
              ],
              "additionalProperties": true
            }
          }
        },
        {
          "type": "object",
          "required": [
            "id",
            "name",
            "subGraphId",
            "type"
          ],
          "properties": {
            "id": {
              "type": "string",
              "format": "uuid"
            },
            "name": {
              "type": "string"
            },
            "subGraphId": {
              "type": "string",
              "format": "uuid"
            },
            "type": {
              "type": "string",
              "enum": [
                "subGraph"
              ]
            },
            "with": {
              "type": [
                "object",
                "null"
              ],
              "additionalProperties": true
            }
          }
        }
      ]
    }
  }
}

=== reearth/reearth-flow/engine/worker/workflow/cms/plateau4/data-convert/bldg/workflow.json
{
  "id": "83307700-04b9-490c-b6a1-11b93e7f7a8a",
  "name": "PLATEAU4-DataConvert-01-bldg-workflow",
  "entryGraphId": "34bf873b-3364-46b0-8153-efeb9568bb3c",
  "with": {
    "cityGmlPath": null,
    "codelists": null,
    "schemas": null,
    "targetPackages": [
      "bldg"
    ]
  },
  "graphs": [
    {
      "id": "c6863b71-953b-4d15-af56-396fc93fc617",
      "name": "FolderAndfilePathReader",
      "nodes": [
        {
          "id": "35038d96-5e81-4a21-a0e0-72f67eb71db5",
          "name": "InputRouter",
          "type": "action",
          "action": "InputRouter",
          "with": {
            "routingPort": "default"
          }
        },
        {
          "id": "c7315341-26b3-4405-9d02-039d721cd225",
          "name": "DirectoryDecompressor",
          "type": "action",
          "action": "DirectoryDecompressor",
          "with": {
            "archiveAttributes": [
              "codelists",
              "schemas"
            ]
          }
        },
        {
          "id": "c73fbb78-74ca-490e-8dc9-e9fa1729bea0",
          "name": "FeatureFilePathExtractor",
          "type": "action",
          "action": "FeatureFilePathExtractor",
          "with": {
            "destPrefix": "udx",
            "sourceDataset": "env.get(\"__value\").cityGmlPath\n",
            "extractArchive": true
          }
        },
        {
          "id": "9d04983e-e84e-4622-b0c6-827d7afad720",
          "name": "FeatureFilter",
          "type": "action",
          "action": "FeatureFilter",
          "with": {
            "conditions": [
              {
                "expr": "env.get(\"__value\").extension == \"gml\"\n",
                "outputPort": "default"
              }
            ]
          }
        },
        {
          "id": "712e4c72-950d-466d-9598-19f299668e7e",
          "name": "PLATEAU4.UDXFolderExtractor",
          "type": "action",
          "action": "PLATEAU4.UDXFolderExtractor",
          "with": {
            "cityGmlPath": "env.get(\"__value\")[\"path\"]\n",
            "codelistsPath": "codelists",
            "schemasPath": "schemas"
          }
        },
        {
          "id": "a1554a74-3caa-4880-a4a3-6dc4ab526a13",
          "name": "FeatureFilterByPackage",
          "type": "action",
          "action": "FeatureFilter",
          "with": {
            "conditions": [
              {
                "expr": "(env.get(\"targetPackages\") ?? []).is_empty() || env.get(\"__value\")[\"package\"] in env.get(\"targetPackages\")\n",
                "outputPort": "default"
              }
            ]
          }
        },
        {
          "id": "f3465c78-59fa-4307-bc02-67c46c2ddd98",
          "name": "FeatureCounterByUdxDirs",
          "type": "action",
          "action": "FeatureCounter",
          "with": {
            "countStart": 1,
            "groupBy": [
              "udxDirs"
            ],
            "outputAttribute": "fileIndex"
          }
        },
        {
          "id": "7bad5b43-6e59-4f6b-95c4-b3043d2b950d",
          "name": "CityCodeExtractor",
          "type": "action",
          "action": "PLATEAU4.CityCodeExtractor",
          "with": {
            "codelistsPathAttribute": "dirCodelists",
            "cityCodeAttribute": "cityCode"
          }
        },
        {
          "id": "9fccbcdb-ab58-4fda-9a47-05a45c84a7fb",
          "name": "OutputRouter",
          "type": "action",
          "action": "OutputRouter",
          "with": {
            "routingPort": "default"
          }
        }
      ],
      "edges": [
        {
          "id": "5d700a9c-1537-442e-bfb2-0728a9e1ec9c",
          "from": "35038d96-5e81-4a21-a0e0-72f67eb71db5",
          "to": "c7315341-26b3-4405-9d02-039d721cd225",
          "fromPort": "default",
          "toPort": "default"
        },
        {
          "id": "749d8e90-dbc3-4fc9-bfee-046344f5f5b9",
          "from": "c7315341-26b3-4405-9d02-039d721cd225",
          "to": "c73fbb78-74ca-490e-8dc9-e9fa1729bea0",
          "fromPort": "default",
          "toPort": "default"
        },
        {
          "id": "1379a497-9e4e-40fb-8361-d2eeeb491762",
          "from": "c73fbb78-74ca-490e-8dc9-e9fa1729bea0",
          "to": "9d04983e-e84e-4622-b0c6-827d7afad720",
          "fromPort": "default",
          "toPort": "default"
        },
        {
          "id": "2379a497-9e4e-40fb-8361-d2eeeb491763",
          "from": "9d04983e-e84e-4622-b0c6-827d7afad720",
          "to": "712e4c72-950d-466d-9598-19f299668e7e",
          "fromPort": "default",
          "toPort": "default"
        },
        {
          "id": "2379a497-9e4e-40fb-8361-d2eeeb491764",
          "from": "712e4c72-950d-466d-9598-19f299668e7e",
          "to": "a1554a74-3caa-4880-a4a3-6dc4ab526a13",
          "fromPort": "default",
          "toPort": "default"
        },
        {
          "id": "2379a497-9e4e-40fb-8361-d2eeeb491766",
          "from": "a1554a74-3caa-4880-a4a3-6dc4ab526a13",
          "to": "f3465c78-59fa-4307-bc02-67c46c2ddd98",
          "fromPort": "default",
          "toPort": "default"
        },
        {
          "id": "0f43aebf-caf7-4f07-be97-f23b9c2c585f",
          "from": "f3465c78-59fa-4307-bc02-67c46c2ddd98",
          "to": "7bad5b43-6e59-4f6b-95c4-b3043d2b950d",
          "fromPort": "default",
          "toPort": "default"
        },
        {
          "id": "80462b53-a06a-4e0b-bed8-07dcda744a55",
          "from": "7bad5b43-6e59-4f6b-95c4-b3043d2b950d",
          "to": "9fccbcdb-ab58-4fda-9a47-05a45c84a7fb",
          "fromPort": "default",
          "toPort": "default"
        }
      ]
    },
    {
      "id": "34bf873b-3364-46b0-8153-efeb9568bb3c",
      "name": "entry_point",
      "nodes": [
        {
          "id": "90f40a3e-61d3-48e2-a328-e7226c2ad1ae",
          "name": "FeatureCreator",
          "type": "action",
          "action": "FeatureCreator",
          "with": {
            "creator": "[\n  #{\n    cityGmlPath: env.get(\"cityGmlPath\"),\n    cityCode: file::extract_filename(env.get(\"cityGmlPath\"))[0..5],\n    codelists: env.get(\"codelists\"),\n    schemas: env.get(\"schemas\"),\n  },\n]\n"
          }
        },
        {
          "id": "d376f32b-7ce8-4721-8b9e-bfa39d71b860",
          "name": "FolderAndFilePathReader",
          "type": "subGraph",
          "subGraphId": "c6863b71-953b-4d15-af56-396fc93fc617"
        },
        {
          "id": "ded2e272-e05c-4918-86b3-aa9f763da6e6",
          "name": "FeatureReaderByCityGml",
          "type": "action",
          "action": "FeatureReader",
          "with": {
            "format": "citygml",
            "dataset": "env.get(\"__value\")[\"path\"]\n"
          }
        },
        {
          "id": "dc498449-5478-4bff-abaa-59f2d160925f",
          "name": "PLATEAU4.MaxLodExtractor",
          "type": "action",
          "action": "PLATEAU4.MaxLodExtractor",
          "with": {
            "cityGmlPathAttribute": "path",
            "maxLodAttribute": "maxLod"
          }
        },
        {
          "id": "1fb4ce1c-538a-436d-8dfa-79185e032de3",
          "name": "AttributeAggregatorByMaxLod",
          "type": "action",
          "action": "AttributeAggregator",
          "with": {
            "aggregateAttributes": [
              {
                "newAttribute": "file",
                "attributeValue": "file::extract_filename(env.get(\"__value\")[\"path\"])\n"
              },
              {
                "newAttribute": "type",
                "attributeValue": "env.get(\"__feature_type\")\n"
              },
              {
                "newAttribute": "maxLod",
                "attributeValue": "env.get(\"__value\").maxLod\n"
              }
            ],
            "calculation": "1\n",
            "calculationAttribute": "count",
            "method": "count"
          }
        },
        {
          "id": "52ff7b3c-5fbb-4ad2-86d9-5df50429e3b4",
          "name": "AttributeMapperByMaxLod",
          "type": "action",
          "action": "AttributeMapper",
          "with": {
            "mappers": [
              {
                "attribute": "code",
                "expr": "env.get(\"__value\").file[0..6]\n"
              },
              {
                "attribute": "type",
                "expr": "env.get(\"__value\")[\"type\"].split(\":\")[0]\n"
              },
              {
                "attribute": "maxLod",
                "expr": "env.get(\"__value\").maxLod\n"
              },
              {
                "attribute": "file",
                "expr": "env.get(\"__value\").file\n"
              }
            ]
          }
        },
        {
          "id": "65074ffc-9113-4fbf-8957-9ba1de4c56ab",
          "name": "FileWriterTsvFilePath",
          "type": "action",
          "action": "FileWriter",
          "with": {
            "format": "csv",
            "output": "file::join_path(env.get(\"workerArtifactPath\"), \"maxLod.csv\")\n"
          }
        },
        {
          "id": "5daabfc0-2bda-4f8d-b206-d7a388469f7a",
          "name": "AttributeFlattener",
          "type": "action",
          "action": "PLATEAU4.AttributeFlattener"
        },
        {
          "id": "8b05f9d4-1cb2-4071-a1da-c968431bc0ec",
          "name": "VerticalReprojector",
          "type": "action",
          "action": "VerticalReprojector",
          "with": {
            "reprojectorType": "jgd2011ToWgs84"
          }
        },
        {
          "id": "3e637368-48dc-48c2-aade-253d5b0cfeeb",
          "name": "AttributeManagerRemoveUnnecessaryAttributes",
          "type": "action",
          "action": "AttributeManager",
          "with": {
            "operations": [
              {
                "attribute": "meshcode",
                "method": "create",
                "value": "file::extract_filename_without_ext(env.get(\"__value\")[\"path\"]).split(\"_\")[0]\n"
              },
              {
                "attribute": "type",
                "method": "rename",
